/**
 * PDF generators for Sokha Chann's chart documents. Each function builds a
 * jsPDF document, opens it in a new tab as a blob URL, and returns the URL so
 * the caller can revoke it if needed.
 *
 * Designed for the prototype demo: realistic medical-report layout (letterhead,
 * patient block, study technique, findings, impression, signature) with
 * believable-looking imagery drawn directly with jsPDF primitives so the
 * bundle stays light.
 */

import jsPDF from "jspdf";

// ── Shared patient block ────────────────────────────────────────────────────
const PATIENT = {
  name: "Sokha Chann",
  mrn: "P-9134",
  dob: "1968-04-12",
  sex: "F",
  ageAt: (years) => 56 + years, // demo seed
};

const CLINIC = {
  name: "Kura Clinic · BKK1",
  address: "55 St. 178, Boeung Keng Kang 1, Phnom Penh",
  phone: "+855 23 555 0142",
  doctor: "Dr. Sopheak Heng, MD",
  license: "MoH-KH-04829",
};

// ── Layout helpers ──────────────────────────────────────────────────────────
const PAGE = { w: 595.28, h: 841.89, margin: 40 }; // A4 portrait, pt

function drawLetterhead(doc, { title, studyDate }) {
  const { margin: m } = PAGE;
  doc.setDrawColor(180);
  doc.setLineWidth(0.5);

  // Clinic block (left)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(20);
  doc.text(CLINIC.name, m, m + 4);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(110);
  doc.text(CLINIC.address, m, m + 16);
  doc.text(CLINIC.phone, m, m + 26);

  // Study title (right)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(20);
  doc.text(title, PAGE.w - m, m + 4, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(110);
  doc.text(`Study date: ${studyDate}`, PAGE.w - m, m + 16, { align: "right" });
  doc.text(`Report ID: KU-${Math.random().toString(36).slice(2, 9).toUpperCase()}`, PAGE.w - m, m + 26, { align: "right" });

  // Rule
  doc.setDrawColor(60);
  doc.setLineWidth(0.8);
  doc.line(m, m + 36, PAGE.w - m, m + 36);

  return m + 50; // y cursor after letterhead
}

function drawPatientBlock(doc, yStart) {
  const { margin: m } = PAGE;
  const colW = (PAGE.w - 2 * m) / 4;

  doc.setFillColor(248, 245, 238);
  doc.rect(m, yStart, PAGE.w - 2 * m, 38, "F");

  doc.setFontSize(7);
  doc.setTextColor(120);
  doc.setFont("helvetica", "bold");
  doc.text("PATIENT", m + 8, yStart + 12);
  doc.text("MRN", m + 8 + colW, yStart + 12);
  doc.text("DOB / SEX", m + 8 + colW * 2, yStart + 12);
  doc.text("REFERRING", m + 8 + colW * 3, yStart + 12);

  doc.setFontSize(10);
  doc.setTextColor(20);
  doc.setFont("helvetica", "normal");
  doc.text(PATIENT.name, m + 8, yStart + 28);
  doc.text(PATIENT.mrn, m + 8 + colW, yStart + 28);
  doc.text(`${PATIENT.dob} · ${PATIENT.sex}`, m + 8 + colW * 2, yStart + 28);
  doc.text(CLINIC.doctor, m + 8 + colW * 3, yStart + 28);

  return yStart + 50;
}

function drawSectionHeader(doc, label, y) {
  const { margin: m } = PAGE;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(60);
  doc.text(label.toUpperCase(), m, y);
  doc.setDrawColor(200);
  doc.setLineWidth(0.4);
  doc.line(m, y + 4, PAGE.w - m, y + 4);
  return y + 14;
}

function drawFooter(doc, pageNum, totalPages) {
  const { margin: m } = PAGE;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(140);
  doc.text(`${CLINIC.doctor} · License ${CLINIC.license}`, m, PAGE.h - 24);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE.w - m, PAGE.h - 24, { align: "right" });
  doc.setDrawColor(220);
  doc.line(m, PAGE.h - 32, PAGE.w - m, PAGE.h - 32);
  doc.setFontSize(6.5);
  doc.text(
    "Confidential medical record. Generated by Kura Health · This electronic document is signed and audit-logged.",
    PAGE.w / 2,
    PAGE.h - 14,
    { align: "center" }
  );
}

// ── ECG waveform drawing ────────────────────────────────────────────────────

// A single PQRST cycle, parameterised. Returns array of [x,y] offsets.
function ecgWavePoints(opts = {}) {
  const { qrsAmp = 12, sAmp = 0, tAmp = 3, baseline = 0 } = opts;
  // Roughly: flat → small P → flat → big QRS → flat → T → flat
  const pts = [];
  const push = (x, y) => pts.push([x, baseline - y]);
  // baseline before P
  for (let x = 0; x < 8; x += 1) push(x, 0);
  // P wave (small bump)
  push(8, 0); push(10, 1.2); push(12, 1.6); push(14, 1.2); push(16, 0);
  // PR segment
  push(18, 0); push(20, 0); push(22, 0);
  // Q (small dip)
  push(23, -1);
  // R (tall spike up)
  push(24, qrsAmp);
  // S (sharp down)
  push(25, -sAmp);
  // back to baseline
  push(27, 0); push(29, 0);
  // T wave
  push(32, tAmp); push(35, tAmp * 1.4); push(38, tAmp); push(41, 0);
  // baseline to end
  for (let x = 43; x < 60; x += 2) push(x, 0);
  return pts;
}

function drawECGGrid(doc, x, y, w, h) {
  // 1mm small squares, 5mm large squares — pink/red
  const sm = 4; // pt per small square (visual approx)
  const lg = sm * 5;

  doc.setLineWidth(0.15);
  doc.setDrawColor(255, 200, 200);
  for (let gx = 0; gx <= w; gx += sm) doc.line(x + gx, y, x + gx, y + h);
  for (let gy = 0; gy <= h; gy += sm) doc.line(x, y + gy, x + w, y + gy);

  doc.setLineWidth(0.35);
  doc.setDrawColor(220, 100, 100);
  for (let gx = 0; gx <= w; gx += lg) doc.line(x + gx, y, x + gx, y + h);
  for (let gy = 0; gy <= h; gy += lg) doc.line(x, y + gy, x + w, y + gy);
}

function drawECGTrace(doc, x, y, label, opts) {
  const w = 130;
  const h = 60;
  drawECGGrid(doc, x, y, w, h);

  // Lead label
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(60);
  doc.text(label, x + 3, y + 9);

  // Calibration mark (1mV step at start)
  doc.setDrawColor(20);
  doc.setLineWidth(0.7);
  const cy = y + h / 2;
  doc.line(x + 14, cy, x + 16, cy);
  doc.line(x + 16, cy, x + 16, cy - 10);
  doc.line(x + 16, cy - 10, x + 18, cy - 10);
  doc.line(x + 18, cy - 10, x + 18, cy);
  doc.line(x + 18, cy, x + 20, cy);

  // Three beats across the lead
  doc.setLineWidth(0.7);
  doc.setDrawColor(20);
  const cycleW = 36;
  const startX = x + 22;
  const pts = ecgWavePoints(opts);
  for (let beat = 0; beat < 3; beat += 1) {
    const ox = startX + beat * cycleW;
    let prev = null;
    for (const [px, py] of pts) {
      const cx = ox + (px / 60) * cycleW;
      const cyAdj = cy - py * 1.2;
      if (prev) doc.line(prev[0], prev[1], cx, cyAdj);
      prev = [cx, cyAdj];
    }
  }
}

// ── 1. Resting 12-lead ECG ──────────────────────────────────────────────────

function buildECG(doc) {
  // Page 1: 12-lead grid
  let y = drawLetterhead(doc, { title: "Resting 12-lead ECG", studyDate: "2025-09-10" });
  y = drawPatientBlock(doc, y);

  y = drawSectionHeader(doc, "Technique", y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(40);
  doc.text("Standard 12-lead acquisition · 25 mm/s · 10 mm/mV · 0.05–150 Hz · supine, post 5 min rest", PAGE.margin, y);
  y += 16;

  y = drawSectionHeader(doc, "12-lead tracing", y);

  // 3 rows × 4 columns of leads. LVH-flavoured: tall R in V5/V6, deep S in V1.
  const leads = [
    [{ l: "I",   o: { qrsAmp: 8 } },  { l: "aVR", o: { qrsAmp: -6, sAmp: 3 } }, { l: "V1", o: { qrsAmp: 2, sAmp: 16 } }, { l: "V4", o: { qrsAmp: 14 } }],
    [{ l: "II",  o: { qrsAmp: 10 } }, { l: "aVL", o: { qrsAmp: 5 } },           { l: "V2", o: { qrsAmp: 6, sAmp: 12 } }, { l: "V5", o: { qrsAmp: 22 } }],
    [{ l: "III", o: { qrsAmp: 6 } },  { l: "aVF", o: { qrsAmp: 9 } },           { l: "V3", o: { qrsAmp: 10, sAmp: 6 } }, { l: "V6", o: { qrsAmp: 18 } }],
  ];

  const m = PAGE.margin;
  for (let r = 0; r < leads.length; r += 1) {
    for (let c = 0; c < leads[r].length; c += 1) {
      const lead = leads[r][c];
      drawECGTrace(doc, m + c * 130, y + r * 65, lead.l, lead.o);
    }
  }
  y += 3 * 65 + 8;

  // Rhythm strip (long lead II)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(60);
  doc.text("II (rhythm strip)", m + 3, y + 9);
  const rhythmW = PAGE.w - 2 * m;
  const rhythmH = 50;
  drawECGGrid(doc, m, y, rhythmW, rhythmH);
  doc.setLineWidth(0.7);
  doc.setDrawColor(20);
  const cy = y + rhythmH / 2;
  const cycleW = 50;
  for (let beat = 0; beat < Math.floor(rhythmW / cycleW); beat += 1) {
    const ox = m + 6 + beat * cycleW;
    let prev = null;
    for (const [px, py] of ecgWavePoints({ qrsAmp: 10 })) {
      const cx = ox + (px / 60) * cycleW;
      const cyAdj = cy - py * 1.0;
      if (prev) doc.line(prev[0], prev[1], cx, cyAdj);
      prev = [cx, cyAdj];
    }
  }

  drawFooter(doc, 1, 2);

  // Page 2: measurements + interpretation
  doc.addPage();
  let y2 = drawLetterhead(doc, { title: "Resting 12-lead ECG · Interpretation", studyDate: "2025-09-10" });
  y2 = drawPatientBlock(doc, y2);

  y2 = drawSectionHeader(doc, "Measurements", y2);

  const rows = [
    ["Ventricular rate",      "78 bpm"],
    ["PR interval",           "162 ms"],
    ["QRS duration",          "94 ms"],
    ["QT / QTc (Bazett)",     "388 ms / 442 ms"],
    ["P axis · QRS · T axis", "62° · +18° · 38°"],
    ["Sokolow-Lyon (S in V1 + R in V5)", "16 + 22 = 38 mm  ▲"],
    ["Cornell voltage (R in aVL + S in V3)",  "5 + 12 = 17 mm"],
  ];
  doc.setFontSize(9.5);
  doc.setTextColor(20);
  doc.setFont("helvetica", "normal");
  for (const [label, val] of rows) {
    doc.setTextColor(110);
    doc.text(label, PAGE.margin + 4, y2);
    doc.setTextColor(20);
    doc.text(val, PAGE.margin + 280, y2);
    y2 += 14;
  }
  y2 += 4;

  y2 = drawSectionHeader(doc, "Interpretation", y2);
  doc.setFontSize(9.5);
  doc.setTextColor(20);
  const findings = [
    "1. Sinus rhythm at 78 bpm. Normal axis. PR, QRS, and QTc within normal limits.",
    "2. Left ventricular hypertrophy by Sokolow-Lyon criteria (38 mm; threshold 35 mm). Cornell",
    "   voltage 17 mm — does not meet Cornell threshold (>20 mm men / >28 mm women).",
    "3. No acute ischemic changes. No ST-segment elevation or depression. T waves are concordant.",
    "4. No conduction abnormalities. No pathologic Q waves.",
  ];
  for (const line of findings) {
    doc.text(line, PAGE.margin + 4, y2);
    y2 += 13;
  }
  y2 += 8;

  y2 = drawSectionHeader(doc, "Impression", y2);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(180, 100, 30);
  doc.text("Sinus rhythm · LVH criteria met (Sokolow-Lyon)", PAGE.margin + 4, y2);
  y2 += 14;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(80);
  doc.text(
    "Findings are consistent with longstanding hypertension. Recommend echocardiography to assess",
    PAGE.margin + 4,
    y2
  );
  y2 += 12;
  doc.text("LV wall thickness and function. Optimise BP control.", PAGE.margin + 4, y2);
  y2 += 24;

  drawSignature(doc, y2);
  drawFooter(doc, 2, 2);
}

function drawSignature(doc, y) {
  const m = PAGE.margin;
  doc.setDrawColor(160);
  doc.setLineWidth(0.4);
  doc.line(m + 4, y + 18, m + 200, y + 18);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(12);
  doc.setTextColor(50);
  doc.text("S. Heng", m + 12, y + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(110);
  doc.text(CLINIC.doctor, m + 4, y + 30);
  doc.text(`Signed electronically · ${new Date().toISOString().slice(0, 10)}`, m + 4, y + 40);
}

// ── 2. Chest X-ray ──────────────────────────────────────────────────────────

function drawChestImage(doc, x, y, w, h) {
  // Black film background
  doc.setFillColor(15, 15, 18);
  doc.rect(x, y, w, h, "F");

  // Soft tissue / lung field gradient — approximated with darker rects
  const cx = x + w / 2;

  // Ribs (curved lines)
  doc.setDrawColor(220, 220, 215);
  doc.setLineWidth(0.5);
  for (let i = 0; i < 9; i += 1) {
    const ry = y + 28 + i * 16;
    // Left side rib
    doc.line(x + 24, ry, cx - 14, ry + 4);
    // Right side rib
    doc.line(cx + 14, ry + 4, x + w - 24, ry);
  }

  // Clavicles
  doc.setLineWidth(1.4);
  doc.setDrawColor(240);
  doc.line(x + 30, y + 30, cx - 10, y + 38);
  doc.line(cx + 10, y + 38, x + w - 30, y + 30);

  // Spine — vertical column of vertebrae
  doc.setLineWidth(2.2);
  doc.setDrawColor(180);
  doc.line(cx, y + 20, cx, y + h - 14);
  doc.setLineWidth(0.4);
  for (let i = 0; i < 12; i += 1) {
    doc.line(cx - 4, y + 26 + i * 12, cx + 4, y + 26 + i * 12);
  }

  // Heart silhouette (cardiac shadow, slightly to the left)
  doc.setFillColor(60, 60, 65);
  // Approx heart shape with two triangles
  doc.triangle(cx - 6, y + 90, cx - 60, y + 130, cx - 6, y + 180, "F");
  doc.triangle(cx - 6, y + 90, cx + 22, y + 110, cx + 22, y + 180, "F");
  doc.triangle(cx - 60, y + 180, cx + 22, y + 180, cx - 18, y + 200, "F");

  // Diaphragm — two curves
  doc.setFillColor(75, 75, 80);
  doc.triangle(x + 24, y + h - 60, cx - 4, y + h - 90, cx - 4, y + h - 50, "F");
  doc.triangle(cx + 4, y + h - 90, x + w - 24, y + h - 60, cx + 4, y + h - 50, "F");

  // Outer chest wall (rounded outline)
  doc.setDrawColor(200);
  doc.setLineWidth(1);
  doc.line(x + 20, y + 20, x + 20, y + h - 30);
  doc.line(x + w - 20, y + 20, x + w - 20, y + h - 30);
  doc.line(x + 20, y + h - 30, x + w - 20, y + h - 30);

  // Markers
  doc.setFontSize(10);
  doc.setTextColor(240);
  doc.text("R", x + 8, y + 16);
  doc.text("L", x + w - 14, y + 16);

  // PA marker
  doc.setFontSize(8);
  doc.setTextColor(180);
  doc.text("PA · upright · inspiration", x + 8, y + h - 8);
}

function buildChestXray(doc) {
  let y = drawLetterhead(doc, { title: "Chest radiograph · PA + AP", studyDate: "2025-06-22" });
  y = drawPatientBlock(doc, y);

  y = drawSectionHeader(doc, "Indication", y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(40);
  doc.text("Hypertension. Baseline cardiopulmonary survey.", PAGE.margin + 4, y);
  y += 18;

  y = drawSectionHeader(doc, "Technique", y);
  doc.setFontSize(9.5);
  doc.setTextColor(40);
  doc.text("PA and AP projections. 120 kVp · 4 mAs · 180 cm SID · upright · full inspiration.", PAGE.margin + 4, y);
  y += 18;

  y = drawSectionHeader(doc, "Image", y);
  const imgW = 230;
  const imgH = 290;
  const imgX = (PAGE.w - imgW) / 2;
  drawChestImage(doc, imgX, y, imgW, imgH);
  y += imgH + 14;

  y = drawSectionHeader(doc, "Findings", y);
  doc.setFontSize(9.5);
  doc.setTextColor(20);
  const findings = [
    "Cardiac silhouette: Normal size, cardiothoracic ratio 0.48. No mediastinal widening.",
    "Lungs: Clear bilaterally. No focal consolidation, mass, or pleural effusion.",
    "Pleura: No pneumothorax. Costophrenic angles sharp.",
    "Hila: Normal contour. No lymphadenopathy.",
    "Bones / soft tissues: No acute fracture. No suspicious osseous lesion.",
  ];
  for (const line of findings) {
    doc.text("• " + line, PAGE.margin + 4, y);
    y += 13;
  }
  y += 8;

  y = drawSectionHeader(doc, "Impression", y);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(20, 130, 90);
  doc.text("No acute cardiopulmonary findings.", PAGE.margin + 4, y);
  y += 24;

  drawSignature(doc, y);
  drawFooter(doc, 1, 1);
}

// ── 3. Abdominal ultrasound ─────────────────────────────────────────────────

function drawUSPanel(doc, x, y, w, h, { label, annotations = [] }) {
  // Black image area with fan-shaped probe outline
  doc.setFillColor(10, 10, 14);
  doc.rect(x, y, w, h, "F");

  // Faux ultrasound sweep — light grayscale specks
  doc.setDrawColor(220);
  doc.setLineWidth(0.2);
  for (let i = 0; i < 80; i += 1) {
    const px = x + 4 + Math.random() * (w - 8);
    const py = y + 4 + Math.random() * (h - 8);
    doc.line(px, py, px + 0.6, py + 0.6);
  }

  // Soft organ silhouette — irregular blob
  doc.setFillColor(70, 70, 75);
  doc.triangle(x + w * 0.25, y + h * 0.35, x + w * 0.7, y + h * 0.25, x + w * 0.5, y + h * 0.7, "F");
  doc.triangle(x + w * 0.25, y + h * 0.35, x + w * 0.5, y + h * 0.7, x + w * 0.15, y + h * 0.55, "F");
  doc.setFillColor(95, 95, 100);
  doc.triangle(x + w * 0.4, y + h * 0.45, x + w * 0.65, y + h * 0.4, x + w * 0.55, y + h * 0.6, "F");

  // Measurement markers (calipers)
  doc.setDrawColor(250, 230, 100);
  doc.setLineWidth(0.6);
  doc.line(x + w * 0.32, y + h * 0.4, x + w * 0.62, y + h * 0.55);
  doc.setFontSize(6.5);
  doc.setTextColor(250, 230, 100);
  doc.text("+", x + w * 0.31, y + h * 0.4 + 1);
  doc.text("+", x + w * 0.62, y + h * 0.55 + 1);

  // Border
  doc.setDrawColor(140);
  doc.setLineWidth(0.6);
  doc.rect(x, y, w, h, "S");

  // Label inside top-left
  doc.setFontSize(7.5);
  doc.setTextColor(240);
  doc.text(label, x + 6, y + 10);

  // Annotation strip below
  doc.setFontSize(7.5);
  doc.setTextColor(60);
  let ay = y + h + 10;
  for (const ann of annotations) {
    doc.text(ann, x, ay);
    ay += 10;
  }
}

function buildAbdominalUS(doc) {
  // ── Page 1: cover ────────────────────────────────────────────────────────
  let y = drawLetterhead(doc, { title: "Abdominal ultrasound", studyDate: "2025-08-04" });
  y = drawPatientBlock(doc, y);

  y = drawSectionHeader(doc, "Indication", y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(40);
  doc.text("Elevated ALT/AST. Screening for hepatic steatosis. Type 2 diabetes mellitus.", PAGE.margin + 4, y);
  y += 18;

  y = drawSectionHeader(doc, "Technique", y);
  doc.text("Real-time B-mode ultrasound. Curvilinear 2–5 MHz probe. NPO ≥6 hours.", PAGE.margin + 4, y);
  y += 16;
  doc.text("Survey of liver, gallbladder, biliary tree, pancreas, spleen, kidneys, aorta, bladder.", PAGE.margin + 4, y);
  y += 20;

  y = drawSectionHeader(doc, "Summary of measurements", y);
  const measurements = [
    ["Liver span (MCL)",        "16.4 cm  ▲ (upper limit 15.5)"],
    ["Hepatic echogenicity",    "Diffusely increased"],
    ["Hepatorenal index",       "1.6 (consistent with steatosis)"],
    ["Gallbladder wall",        "2 mm · normal"],
    ["CBD",                     "4 mm · normal"],
    ["Right kidney",            "10.8 × 4.6 cm · normal"],
    ["Left kidney",             "11.1 × 4.8 cm · normal"],
    ["Spleen",                  "10.2 cm · normal"],
    ["Aorta (max diameter)",    "1.8 cm · normal"],
    ["Bladder",                 "Well-distended · no wall thickening"],
  ];
  doc.setFontSize(9.5);
  for (const [label, val] of measurements) {
    doc.setTextColor(110);
    doc.text(label, PAGE.margin + 4, y);
    doc.setTextColor(20);
    doc.text(val, PAGE.margin + 240, y);
    y += 13;
  }
  drawFooter(doc, 1, 4);

  // ── Page 2: liver ────────────────────────────────────────────────────────
  doc.addPage();
  let y2 = drawLetterhead(doc, { title: "Abdominal ultrasound · Liver & biliary", studyDate: "2025-08-04" });
  y2 = drawPatientBlock(doc, y2);

  y2 = drawSectionHeader(doc, "Liver", y2);
  const panelW = (PAGE.w - 2 * PAGE.margin - 14) / 2;
  drawUSPanel(doc, PAGE.margin, y2, panelW, 130, {
    label: "LIVER · right lobe · transverse",
    annotations: ["Diffuse hyperechoic parenchyma vs. renal cortex.", "No focal lesion. Vessels appear blurred — consistent with steatosis."],
  });
  drawUSPanel(doc, PAGE.margin + panelW + 14, y2, panelW, 130, {
    label: "LIVER · left lobe · sagittal",
    annotations: ["Smooth contour. No surface nodularity.", "Span 16.4 cm at MCL — borderline hepatomegaly."],
  });
  y2 += 130 + 38;

  y2 = drawSectionHeader(doc, "Gallbladder & biliary tree", y2);
  drawUSPanel(doc, PAGE.margin, y2, panelW, 130, {
    label: "GALLBLADDER · long axis",
    annotations: ["Anechoic lumen. Wall 2 mm.", "No calculi, sludge, or pericholecystic fluid."],
  });
  drawUSPanel(doc, PAGE.margin + panelW + 14, y2, panelW, 130, {
    label: "CBD · porta hepatis",
    annotations: ["CBD 4 mm — non-dilated.", "No intrahepatic ductal dilatation."],
  });

  drawFooter(doc, 2, 4);

  // ── Page 3: kidneys + pancreas + spleen ──────────────────────────────────
  doc.addPage();
  let y3 = drawLetterhead(doc, { title: "Abdominal ultrasound · Kidneys & retroperitoneum", studyDate: "2025-08-04" });
  y3 = drawPatientBlock(doc, y3);

  y3 = drawSectionHeader(doc, "Kidneys", y3);
  drawUSPanel(doc, PAGE.margin, y3, panelW, 130, {
    label: "RIGHT KIDNEY · long axis",
    annotations: ["10.8 × 4.6 cm. Cortical thickness 1.4 cm.", "Normal corticomedullary differentiation."],
  });
  drawUSPanel(doc, PAGE.margin + panelW + 14, y3, panelW, 130, {
    label: "LEFT KIDNEY · long axis",
    annotations: ["11.1 × 4.8 cm. Cortical thickness 1.5 cm.", "No hydronephrosis. No calculi."],
  });
  y3 += 130 + 38;

  y3 = drawSectionHeader(doc, "Pancreas & spleen", y3);
  drawUSPanel(doc, PAGE.margin, y3, panelW, 130, {
    label: "PANCREAS · transverse",
    annotations: ["Visualised head, body, tail.", "Normal echogenicity. Duct non-dilated."],
  });
  drawUSPanel(doc, PAGE.margin + panelW + 14, y3, panelW, 130, {
    label: "SPLEEN · long axis",
    annotations: ["10.2 cm. Homogeneous parenchyma.", "No focal lesion."],
  });

  drawFooter(doc, 3, 4);

  // ── Page 4: impression ──────────────────────────────────────────────────
  doc.addPage();
  let y4 = drawLetterhead(doc, { title: "Abdominal ultrasound · Impression", studyDate: "2025-08-04" });
  y4 = drawPatientBlock(doc, y4);

  y4 = drawSectionHeader(doc, "Findings", y4);
  doc.setFontSize(9.5);
  doc.setTextColor(20);
  const findings = [
    "1. Diffuse increased hepatic echogenicity with blurring of vascular margins and posterior",
    "   attenuation. Hepatorenal index 1.6. Findings consistent with hepatic steatosis, mild.",
    "2. Mild hepatomegaly (16.4 cm at MCL).",
    "3. Gallbladder, biliary tree, pancreas, spleen, kidneys, aorta, and bladder unremarkable.",
    "4. No free intraperitoneal fluid.",
  ];
  for (const line of findings) {
    doc.text(line, PAGE.margin + 4, y4);
    y4 += 13;
  }
  y4 += 12;

  y4 = drawSectionHeader(doc, "Impression", y4);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(180, 100, 30);
  doc.text("Hepatic steatosis · mild. No other acute abdominal pathology.", PAGE.margin + 4, y4);
  y4 += 22;

  y4 = drawSectionHeader(doc, "Recommendations", y4);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(40);
  const recs = [
    "• Lifestyle: weight loss 7–10% of body weight, Mediterranean diet, regular aerobic exercise.",
    "• Optimise glycemic control (HbA1c target <7.0%).",
    "• Address dyslipidaemia (current LDL 162 mg/dL → statin therapy).",
    "• Repeat US in 12 months. Consider FibroScan if ALT remains elevated >6 months.",
  ];
  for (const line of recs) {
    doc.text(line, PAGE.margin + 4, y4);
    y4 += 13;
  }
  y4 += 18;

  drawSignature(doc, y4);
  drawFooter(doc, 4, 4);
}

// ── Public API ──────────────────────────────────────────────────────────────

function openPdf(builderFn, filename) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  builderFn(doc);
  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  // Open inline in a new tab. The browser's PDF viewer handles render + download.
  window.open(url, "_blank", "noopener,noreferrer");
  // Revoke after a delay so the browser has time to fetch.
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
  return { url, filename };
}

export function openEcgPdf() {
  return openPdf(buildECG, "sokha-chann-ecg.pdf");
}

export function openChestXrayPdf() {
  return openPdf(buildChestXray, "sokha-chann-chest-xray.pdf");
}

export function openAbdominalUsPdf() {
  return openPdf(buildAbdominalUS, "sokha-chann-abdominal-us.pdf");
}

export function openDocumentPdf(kind) {
  if (kind === "ECG") return openEcgPdf();
  if (kind === "X-ray") return openChestXrayPdf();
  if (kind === "Ultrasound") return openAbdominalUsPdf();
  return null;
}
